### ISSUE TITLE
Homepage Nav

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/portfolio#12]
homepage navigation images (hamburger/x) don't show up once jekyll was added 
still clickable and usable, just doesn't show up
shows up on portfolio page 

@thomasjbradley

**Comment by thomasjbradley** [comment]
It seems to be the `gutter-2` classes directly on the images, here:
https://github.com/sky-bones/portfolio/blob/gh-pages/_layouts/default.html#L23-L24
Removing them fixes the problem.

**Comment by sky-bones** [comment]
Very strange, but fixed! Thank you! 

(removed gutter-2)
