### ISSUE TITLE
Portfolio page no longer appearing

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/portfolio#13]
@thomasjbradley 

After adding Jekyll, my my portfolio.html page no longer appears on github(live) site. Works locally through the terminal. 

all navigation code has been moved to default.html, and {{site.baseurl}}/ has been added. 

(after restarting jekyll i get this error) 
<img width="378" alt="screen shot 2015-10-17 at 6 18 40 pm" src="https://cloud.githubusercontent.com/assets/6333963/10561558/88a6a3e4-74fb-11e5-854a-cab28c093804.png">

**Comment by thomasjbradley** [comment]
The URLs no longer have `.html` in them because of the pretty permalinks.

Remove the `.html` from here an it'll work:
https://github.com/sky-bones/portfolio/blob/gh-pages/_layouts/default.html#L28

**Comment by sky-bones** [comment]
That fixed it! Thank you! 

(made sure to add site.baseurl tags to all links/images)
