### ISSUE TITLE
type.css overriding main.css 

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/portfolio#19]
I've taken the padding/margin off of my ul, but the margin from type.css is still active and moving things around when it wasn't before. 

It doesn't allows me to change the value (is not affecting it) in my main.css 

@thomasjbradley

**Comment by thomasjbradley** [comment]
It's because the CSS files aren't in the correct order—`main.css` should always go last, like this:
1. grid.css
2. type.css
3. main.css

**Comment by sky-bones** [comment]
Thank you!!!!!!!
