### ISSUE TITLE
FireFox 

### ISSUE THREAD

**Issue by norr0065** [sky-bones/portfolio#2]
Your hamburger drop down is a little bit off in firefox - but I feel like you know that it might just need a little more love :)

**Comment by bradley-doyle** [comment]
the hamburger on safair either isn't complete for large screens or is full on broken ( see image
![screen shot 2015-10-06 at 4 08 06 pm](https://cloud.githubusercontent.com/assets/4565418/10321026/7f7f81d8-6c44-11e5-9666-14d2d94ce4e6.png)

**Comment by sky-bones** [comment]
Nav was broken, added fixes/completions for both issues
