### ISSUE TITLE
Image extension issue 

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/portfolio#24]
I can't remove the .jpg or it break the file path to all of the homepage images. Right now all of them are jpgs, but I've tried to replace some of them with pngs which would be smaller. 

(Line 49 in index.html) 
`<img class="img-flex" src="{{site.baseurl}}/img/thumbs/{{post.imagename}}.jpg" alt="" role="img">`

@thomasjbradley

**Comment by thomasjbradley** [comment]
Change the HTML to this, _removing the .jpg_:

``` html
<img class="img-flex" src="{{site.baseurl}}/img/thumbs/{{post.imagename}}" alt="" role="img">
```

Then add the extension into the post YAML data instead, like this:

``` yml
imagename: accursed.jpg
```

**Comment by sky-bones** [comment]
Thank you!!
