### ISSUE TITLE
Images on portfolio page accursed disappeared  

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/portfolio#34]
the process images for the accursed page disappeared!

all of the other images are there, the file path didn't change, but those three pictures disappeared. (they come up with a 404 in the console) 

this only happened on this page. 

@thomasjbradley

**Comment by thomasjbradley** [comment]
Double check their extensions in your code, the PNGs and JPGs are mixed up.

**Comment by sky-bones** [comment]
well that's' embarrassing... Thanks!!
