### ISSUE TITLE
Android 4.4

### ISSUE THREAD

**Issue by isabelle6** [sky-bones/portfolio#8]
On the work page, some of the images are a little smaller than the screen, and some are a little bigger.
![lizz](https://cloud.githubusercontent.com/assets/6333962/10320913/dae31388-6c43-11e5-87e6-f759db13bbf6.png)

**Comment by grantjeffery** [comment]
Looks good, but the same issue appears on UC Browser.

**Comment by seanokai** [comment]
Good work! Same problem with previous issues mentioned. On Android 5

**Comment by sky-bones** [comment]
Fixed! (hopefully) Thank you!
